version: 2.1
aliases:
  - &container_python
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job

  - &run_task_install_tox_dependencies
    run:
      name: install tox dependencies
      command: |
        sudo printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" | sudo tee /etc/apt/sources.list
        sudo apt-get update
        sudo apt install -y build-essential libssl-dev libpython-dev python python-pip
        sudo pip install --upgrade pip
        sudo pip install tox

jobs:
  testing:
    parameters:
      tests:
        type: string
        default: py27-torch04,py27-torch10,py27-torch11,py36-torch04,py36-torch10,py36-torch11
    <<: *container_python
    steps:
      - checkout
      - *run_task_install_tox_dependencies
      - run:
          name: execute pytests << parameters.tests >>
          command: |
            tox -e << parameters.tests >>
      - store_test_results:
          path: .tox/test/tmp/reports
  builddocs:
    <<: *container_python
    steps:
      - checkout
      - *run_task_install_tox_dependencies
      - run:
          name: build the sphinx documentation
          command: |
            tox -e docs

workflows:
  version: 2
  build_and_test:
    jobs:
      - testing:
          name: testing_py27_torch04
          tests: py27_torch04
      - testing:
          name: testing_py27_torch10
          tests: py27_torch10
      - testing:
          name: testing_py27_torch11
          tests: py27_torch11
      - testing:
          name: testing_py36_torch04
          tests: py36_torch04
      - testing:
          name: testing_py36_torch10
          tests: py36_torch10
      - testing:
          name: testing_py36_torch11
          tests: py36_torch11
      - builddocs
